import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <nav>
          <h1>Logo</h1>
          <Link href={'/ssr'}>Go To SSR</Link>
          <br />
          <Link href={'/csr'}>Go To CSR</Link>
          <br />
          <Link href={'/static'}>Go To SSG</Link>
          <br />
          <Link href={'/'}>Home</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
